example/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

/**
 * User
 */
Route::resource('user','UserController');

/**
 * Admin
 */
Route::get('admin','FrontController@admin');
Route::get('home','FrontController@index');
Route::resource('log','LogController');
Route::get('unauthorized','LogController@unauthorized');
Route::get('logout','LogController@logout');

/**
 * Products
 */
Route::resource('product','ProductController');
Route::get('getProducts','ProductController@listing');
Route::post('createProduct','ProductController@storeProduct');
Route::put('updateProduct','ProductController@updateProduct');

/**
 * Roles
 */
Route::resource('rol','RolController');
Route::get('getRoles','RolController@listing');

/**
 * Files
 */
Route::resource('file','FileController');


/**
 * Mail
 */

Route::resource('mail','MailController');

 /**
  * Category
  */
Route::resource('category','CategoryController');
Route::get('listingCategories','CategoryController@listing');

/**
 * Expense
 */
Route::resource('expense','ExpenseController');

/**
 * Incomes
 */
Route::resource('income','IncomeController');


 
Route::post('api/create','ApiController@store')->middleware('accesskey');

example/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //protected $table    = 'products';
     
    const TABLE         = "products";
    const CLASS_NAME    = __CLASS__;
    const ID            = "id";
    const NAME          = "name";
    const DESCRIPTION   = 'description';
    const PRICE         = 'price';
    const STATUS        = 'status';
    const CREATED_AT    = 'created_at';
    const UPDATED_AT    = 'updated_at';

  

    protected $table    = self::TABLE;
    public $timestamps  = false;
    protected $fillable=array(
        self::NAME,
        self::DESCRIPTION,
        self::PRICE
    );
   
}

example/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Http\Requests\ProductRequest;


class ProductController extends Controller
{
    public function index()
    {
        return view('products.index');
    }

    public function create()
    {
        return view('products.create');
    }

    public function store(ProductRequest $request)
    {
        if($request->ajax()){
            try{
                Product::create([
                    'name'=>$request['name'],
                    'description'=>$request['description'],
                    'price'=>$request['price'],
                    'status'=>$request['status']
                ]);
        
                return response()->json([
                    'issuccess'=>true,
                    'message'=>'Usuario creado correctamente',
                    'result'=>''
                ]);
            }
            catch(Exception $e){
                return response()->json([
                    'issuccess'=>false,
                    'message'=>'Usuario creado correctamente '.$e->getMessage(),
                    'result'=>''
                ]);
            }
        }
    }

    public function edit($id)
    {
        $product=Product::find($id);
        return view('products.edit',['product'=>$product]);
    }

    public function update($id, ProductRequest $request)
    {
        if($request->ajax()){
            try{
                $product=Product::find($id);
                $product->fill($request->all());
                $product->save();
    
                return response()->json([
                    'issuccess'=>true,
                    'message'=>'Usuario editado correctamente ',
                    'result'=>''
                ]);
            }
            catch(Exception $e){
                return response()->json([
                    'issuccess'=>false,
                    'message'=>$e->getMessage(),
                    'result'=>''
                ]);
            }
        }  
    }

    public function destroy($id)
    {
        try{
            $product=Product::find($id);
            $product->delete();
            return response()->json([
                'issuccess'=>true,
                'message'=>'Producto eliminado correctamente',
                'result'=>''
            ]);
        }
        catch(Exception $e){
            return response()->json([
                'issuccess'=>false,
                'message'=>$e->getMessage(),
                'result'=>''
            ]);
        }
    }

    /**
     * AJAX
     */

    public function listing()
    {
        $products=Product::all();
        if(count($products)>0){
            return response()->json([
                'issuccess'=>true,
                'message'=>'Se encontrarón datos de productos',
                'result'=>$products
            ]);
        }
        else{
            return response()->json([
                'issuccess'=>false,
                'message'=>'No se encontrarón datos de productos',
                'result'=>''
            ]);
        }
    }
}

example/resources/views/products/create.blade.php
@extends('layouts.main')
@section('content')
    <h1>Crear Producto</h1>

    <div class='col-md-4'></div>
    <div class='col-md-4'>

        <div id="msg-error"></div>

        <a href="/product">Productos</a>

        <form id="form_createProduct">
            <div class='form-group'>
                {!!Form::label('Nombre:')!!}
                {!!Form::text('name',null,['id'=>'name','class'=>'form-control'])!!}
            </div>
            <div class='form-group'>
                {!!Form::label('Descrición:')!!}
                {!!Form::text('description',null,['id'=>'description','class'=>'form-control'])!!}
            </div>
            <div class='form-group'>
                {!!Form::label('Precio:')!!}
                {!!Form::text('price',null,['id'=>'price','class'=>'form-control'])!!}
            </div>
            <div class='form-group'>
                {!!Form::label('Estatus:')!!}
                <input type="checkbox" name="status" id="status" value="0", class="form-control"/>
            </div>
            {!!Form::submit('Crear',['class'=>'btn btn-primary'])!!}
        </form>
    </div>
    <div class='col-md-4'></div>
@stop

example/resources/views/products/edit.blade.php
@extends('layouts.main')
@section('content')
<h1>Crear Producto</h1>

<div class='col-md-4'></div>
<div class='col-md-4'>

    <div id="msg-error"></div>

    <a href="/product">Productos</a>

    {!!Form::model($product,['route'=>['product.update',$product->id],'id' => 'formUpdateProduct','method'=>'PUT'])!!}
        <input type="hidden" id="idproduct" name="idproduct" value="{{$product->id}}"/>
        <div class='form-group'>
            {!!Form::label('Nombre:')!!}
            {!!Form::text('name',null,['id'=>'name','class'=>'form-control'])!!}
        </div>
        <div class='form-group'>
            {!!Form::label('Descrición:')!!}
            {!!Form::text('description',null,['id'=>'description','class'=>'form-control'])!!}
        </div>
        <div class='form-group'>
            {!!Form::label('Precio:')!!}
            {!!Form::text('price',null,['id'=>'price','class'=>'form-control'])!!}
        </div>
        {!!Form::submit('Crear',['class'=>'btn btn-primary'])!!}
    {!!Form::close()!!}
</div>
<div class='col-md-4'></div>
@stop

example/resources/views/products/index.blade.php
@extends('layouts.main')
@section('content')

    {!!link_to_route('product.create',$title='Crear producto',null,$attributes=['class'=>'btn btn-primary'])!!}
    <table class="table">
        <thead>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </thead>
        <tbody id="tbl_product">
                
        </tbody>
    </table>

@stop

 